<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Tablefields;

class TablefieldsSeeder extends Seeder
{
    public function run(): void
    {

        /*
        TÍPUSOK: 
            1 => Alap nem megvehető Start,Börtön
            2 => Meglepetés-Kártya
            3 => Szerencsekártya
            4 => Megvehető Háznélkül vasút,vízmű
            5 => Megvehtő Ház és szálodás
        Tulajdonos: 
            0 => Bank
            99 => Senki, nem értékesíthető
        */
        Tablefields::create([
            'szam' => 1,
            'nev' => 'PIAC TÉR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 6000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#A52A2A',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 2,
            'nev' => 'MEGLEPETÉS-KÁRTYA',
            'leiras' => '',
            'tipus' => 2,
            'ar' => 0,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 3,
            'nev' => 'TÖRÖK UDVAR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 10000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#A52A2A',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 4,
            'nev' => 'JŐVEDELEMADÓ',
            'leiras' => 'Fizess 20000-et',
            'tipus' => 1,
            'ar' => 20000,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 5,
            'nev' => 'ÉSZAKI VASÚTVONAL',
            'leiras' => '',
            'tipus' => 4,
            'ar' => 20000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 6,
            'nev' => 'NAGYKŐRÖSI ÚT',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 10000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#0000FF',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 7,
            'nev' => 'SZERENCSEKÁRTYA',
            'leiras' => '',
            'tipus' => 2,
            'ar' => 0,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#0000FF',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 8,
            'nev' => 'LESTÁR TÉR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 10000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#0000FF',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 9,
            'nev' => 'KISFALUDY ÚT',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 12000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#0000FF',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        //FELSŐ SOR
        Tablefields::create([
            'szam' => 10,
            'nev' => 'BÖRTÖN',
            'leiras' => 'Csak megpihensz',
            'tipus' => 1,
            'ar' => 0,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 11,
            'nev' => 'EGYETEM UTCA',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 14000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FF0000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 12,
            'nev' => 'ELEKTROMOS TÁRSASÁG',
            'leiras' => '',
            'tipus' => 4,
            'ar' => 15000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 13,
            'nev' => 'SZÍNHÁZ TÉR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 15000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FF0000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 14,
            'nev' => 'JANUS PANNONIUS ÚT',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 16000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FF0000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 15,
            'nev' => 'KELETI VASÚTVONAL',
            'leiras' => '',
            'tipus' => 4,
            'ar' => 20000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 16,
            'nev' => 'PETŐFI TÉR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 18000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);

        Tablefields::create([
            'szam' => 17,
            'nev' => 'MEGLEPETÉS-KÁRTYA',
            'leiras' => '',
            'tipus' => 2,
            'ar' => 0,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 18,
            'nev' => 'NAGYERDŐ',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 18000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FFC000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 19,
            'nev' => 'BETHLEN UTCA',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 20000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FFC000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 20,
            'nev' => 'INGYEN PARKOLÓ',
            'leiras' => '',
            'tipus' => 1,
            'ar' => 0,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 21,
            'nev' => 'MÓRA PARK',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 22000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FF0000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 22,
            'nev' => 'SZERENCSE-KÁRTYA',
            'leiras' => '',
            'tipus' => 2,
            'ar' => 0,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FF0000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 23,
            'nev' => 'OSKOLA UTCA',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 22000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FF0000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 24,
            'nev' => 'DÓM TÉR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 24000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FF0000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 25,
            'nev' => 'DÉLI VASÚTVONAL',
            'leiras' => '',
            'tipus' => 4,
            'ar' => 20000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 26,
            'nev' => 'DOBÓ TÉR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 26000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FFFF00',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 27,
            'nev' => 'ALMAGYAR UTCA',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 26000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FFFF00',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 28,
            'nev' => 'VÍZMŰ TÁRSASÁG',
            'leiras' => '',
            'tipus' => 4,
            'ar' => 15000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 29,
            'nev' => 'GÁRDONYI ÚT',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 26000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#FFFF00',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        //ALSÓ SOR
        Tablefields::create([
            'szam' => 30,
            'nev' => 'IRÁNY A BÖRTÖN',
            'leiras' => '',
            'tipus' => 0,
            'ar' => 0,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 31,
            'nev' => 'KŐFARAGÓ TÉR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 30000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#008000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 32,
            'nev' => 'ÓVÁROS',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 30000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#008000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 33,
            'nev' => 'MEGLEPETÉS-KÁRTYA',
            'leiras' => '',
            'tipus' => 2,
            'ar' => 0,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 34,
            'nev' => 'ÖTVÖS UTCA',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 32000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#008000',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 35,
            'nev' => 'NYUGATI VASÚTVONAL',
            'leiras' => '',
            'tipus' => 4,
            'ar' => 20000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 36,
            'nev' => 'SZERENCSEKÁRTYA',
            'leiras' => '',
            'tipus' => 2,
            'ar' => 0,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#0000FF',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 37,
            'nev' => 'VÖRÖSMARTY TÉR',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 35000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#000080',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 38,
            'nev' => 'PÓTADÓ',
            'leiras' => '',
            'tipus' => 1,
            'ar' => 20000,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 39,
            'nev' => 'DUNAKORZÓ',
            'leiras' => '',
            'tipus' => 5,
            'ar' => 40000,
            'tulajdonos_id' => 0,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '#000080',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
        Tablefields::create([
            'szam' => 40,
            'nev' => 'START',
            'leiras' => 'Áthaladás 20.000',
            'tipus' => 1,
            'ar' => 20000,
            'tulajdonos_id' => 99,
            'haz' => 0,
            'szalloda' => 0,
            'szin' => '',
            'kep' => '',
            'created_at' => NULL,
            'updated_at' => NULL,
        ]);
    }
}
